import type { FeedCategory, FeedItem } from '@/features/feed/types';
import type { UserRole } from '@/types/database';

export const FEED_PAGE_SIZE = 15;

export const FEED_FILTERS: { id: FeedCategory; label: string }[] = [
  { id: 'all', label: 'Tümü' },
  { id: 'news', label: 'Haberler' },
  { id: 'emergency', label: 'Acil Durumlar' },
  { id: 'traffic', label: 'Trafik' },
  { id: 'event', label: 'Etkinlikler' },
  { id: 'job', label: 'İş İlanları' },
  { id: 'business', label: 'İşletmeler' },
  { id: 'lost_found', label: 'Kayıp İlanları' },
  { id: 'reels', label: 'Reels' },
  { id: 'following', label: 'Takip Ettiklerim' },
];

export const REPORT_REASONS = [
  { id: 'spam', label: 'Spam' },
  { id: 'harassment', label: 'Hakaret / Taciz' },
  { id: 'fraud', label: 'Dolandırıcılık' },
  { id: 'abuse', label: 'Taciz' },
  { id: 'misinformation', label: 'Yalan Bilgi' },
  { id: 'child_safety', label: 'Çocuk Güvenliği' },
  { id: 'violence', label: 'Şiddet İçeriği' },
] as const;

export const BADGE_CONFIG: Record<
  UserRole,
  { label: string; color: string; icon: string } | null
> = {
  user: null,
  verified_reporter: { label: 'Muhabir', color: '#1E88E5', icon: 'mic' },
  moderator: { label: 'Moderatör', color: '#7B1FA2', icon: 'shield-checkmark' },
  admin: { label: 'Admin', color: '#D32F2F', icon: 'star' },
  super_admin: { label: 'Admin', color: '#D32F2F', icon: 'star' },
};

const DEMO_AUTHOR = {
  id: 'demo-author-1',
  username: 'trabzonhaber',
  fullName: 'Trabzon Haber',
  avatarUrl: null,
  role: 'verified_reporter' as UserRole,
  isVerified: true,
};

export const DEMO_FEED_ITEMS: FeedItem[] = [
  {
    id: 'demo-post-1',
    sourceType: 'post',
    sourceId: 'demo-post-1',
    author: DEMO_AUTHOR,
    title: 'Meydan trafik kazası',
    content: "Trabzon Meydan'da iki araç çarpıştı. Yol tek şeride düştü, ekipler olay yerinde.",
    mediaUrls: [],
    category: 'traffic',
    regionId: 'trabzon',
    district: 'Ortahisar',
    locationLabel: 'Trabzon Meydan',
    latitude: 41.0015,
    longitude: 39.7178,
    likeCount: 128,
    commentCount: 34,
    quoteCount: 12,
    saveCount: 45,
    viewCount: 2840,
    createdAt: new Date(Date.now() - 1000 * 60 * 18).toISOString(),
    isLiked: false,
    isSaved: false,
    isFollowing: false,
    quotedPost: null,
    isDemo: true,
  },
  {
    id: 'demo-post-2',
    sourceType: 'post',
    sourceId: 'demo-post-2',
    author: {
      id: 'demo-author-2',
      username: 'yomra_gundem',
      fullName: 'Yomra Gündem',
      avatarUrl: null,
      role: 'user',
      isVerified: false,
    },
    title: null,
    content: 'Yomra sahilinde bu akşam canlı müzik etkinliği var. #Yomra #Etkinlik',
    mediaUrls: [],
    category: 'event',
    regionId: 'trabzon',
    district: 'Yomra',
    locationLabel: 'Yomra Sahil',
    latitude: 40.9589,
    longitude: 39.8567,
    likeCount: 56,
    commentCount: 8,
    quoteCount: 3,
    saveCount: 21,
    viewCount: 920,
    createdAt: new Date(Date.now() - 1000 * 60 * 55).toISOString(),
    isLiked: false,
    isSaved: false,
    isFollowing: true,
    quotedPost: null,
    isDemo: true,
  },
  {
    id: 'demo-post-3',
    sourceType: 'post',
    sourceId: 'demo-post-3',
    author: {
      id: 'demo-author-3',
      username: 'karadeniz_is',
      fullName: 'Karadeniz İş',
      avatarUrl: null,
      role: 'user',
      isVerified: true,
    },
    title: 'Otel personeli aranıyor',
    content: 'Yaz sezonu için resepsiyon ve servis personeli alınacaktır. Detaylar için DM.',
    mediaUrls: [],
    category: 'job',
    regionId: 'trabzon',
    district: 'Akçaabat',
    locationLabel: 'Akçaabat',
    latitude: null,
    longitude: null,
    likeCount: 19,
    commentCount: 5,
    quoteCount: 1,
    saveCount: 67,
    viewCount: 540,
    createdAt: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    isLiked: false,
    isSaved: false,
    isFollowing: false,
    quotedPost: null,
    isDemo: true,
  },
];
