import type { RegionId } from '@/constants/regions';

export const DISTRICTS: Record<RegionId, string[]> = {
  amasya: ['Merkez', 'Göynücek', 'Gümüşhacıköy', 'Hamamözü', 'Merzifon', 'Suluova', 'Taşova'],
  artvin: ['Merkez', 'Ardanuç', 'Arhavi', 'Borçka', 'Hopa', 'Murgul', 'Şavşat', 'Yusufeli'],
  bartin: ['Merkez', 'Amasra', 'Kurucaşile', 'Ulus'],
  bayburt: ['Merkez', 'Aydıntepe', 'Demirözü'],
  bolu: ['Merkez', 'Dörtdivan', 'Gerede', 'Göynük', 'Kıbrıscık', 'Mengen', 'Mudurnu', 'Seben', 'Yeniçağa'],
  corum: [
    'Merkez',
    'Alaca',
    'Bayat',
    'Boğazkale',
    'Dodurga',
    'İskilip',
    'Kargı',
    'Laçin',
    'Mecitözü',
    'Oğuzlar',
    'Ortaköy',
    'Osmancık',
    'Sungurlu',
    'Uğurludağ',
  ],
  duzce: ['Merkez', 'Akçakoca', 'Cumayeri', 'Çilimli', 'Gölyaka', 'Gümüşova', 'Kaynaşlı', 'Yığılca'],
  giresun: [
    'Merkez',
    'Alucra',
    'Bulancak',
    'Çamoluk',
    'Çanakçı',
    'Dereli',
    'Doğankent',
    'Espiye',
    'Eynesil',
    'Görele',
    'Güce',
    'Keşap',
    'Piraziz',
    'Şebinkarahisar',
    'Tirebolu',
    'Yağlıdere',
  ],
  gumushane: ['Merkez', 'Kelkit', 'Köse', 'Kürtün', 'Şiran', 'Torul'],
  karabuk: ['Merkez', 'Eflani', 'Eskipazar', 'Ovacık', 'Safranbolu', 'Yenice'],
  kastamonu: [
    'Merkez',
    'Abana',
    'Ağlı',
    'Araç',
    'Azdavay',
    'Bozkurt',
    'Cide',
    'Çatalzeytin',
    'Daday',
    'Devrekani',
    'Doğanyurt',
    'Hanönü',
    'İhsangazi',
    'İnebolu',
    'Küre',
    'Pınarbaşı',
    'Seydiler',
    'Şenpazar',
    'Taşköprü',
    'Tosya',
  ],
  ordu: [
    'Altınordu',
    'Akkuş',
    'Aybastı',
    'Çamaş',
    'Çatalpınar',
    'Çaybaşı',
    'Fatsa',
    'Gölköy',
    'Gülyalı',
    'Gürgentepe',
    'İkizce',
    'Kabadüz',
    'Kabataş',
    'Korgan',
    'Kumru',
    'Mesudiye',
    'Perşembe',
    'Ulubey',
    'Ünye',
  ],
  rize: [
    'Merkez',
    'Ardeşen',
    'Çamlıhemşin',
    'Çayeli',
    'Derepazarı',
    'Fındıklı',
    'Güneysu',
    'Hemşin',
    'İkizdere',
    'İyidere',
    'Kalkandere',
    'Pazar',
  ],
  samsun: [
    'Atakum',
    'İlkadım',
    'Canik',
    'Tekkeköy',
    'Alaçam',
    'Asarcık',
    'Ayvacık',
    'Bafra',
    'Çarşamba',
    'Havza',
    'Kavak',
    'Ladik',
    'Ondokuzmayıs',
    'Salıpazarı',
    'Terme',
    'Vezirköprü',
    'Yakakent',
  ],
  sinop: ['Merkez', 'Ayancık', 'Boyabat', 'Dikmen', 'Durağan', 'Erfelek', 'Gerze', 'Saraydüzü', 'Türkeli'],
  tokat: [
    'Merkez',
    'Almus',
    'Artova',
    'Başçiftlik',
    'Erbaa',
    'Niksar',
    'Pazar',
    'Reşadiye',
    'Sulusaray',
    'Turhal',
    'Yeşilyurt',
    'Zile',
  ],
  trabzon: [
    'Ortahisar',
    'Akçaabat',
    'Araklı',
    'Arsin',
    'Beşikdüzü',
    'Çarşıbaşı',
    'Çaykara',
    'Dernekpazarı',
    'Düzköy',
    'Hayrat',
    'Köprübaşı',
    'Maçka',
    'Of',
    'Sürmene',
    'Şalpazarı',
    'Tonya',
    'Vakfıkebir',
    'Yomra',
  ],
  zonguldak: ['Merkez', 'Alaplı', 'Çaycuma', 'Devrek', 'Ereğli', 'Gökçebey', 'Kilimli', 'Kozlu'],
};
