export const NOTIFICATION_CATEGORIES = [
  { id: 'all', label: 'Tümü' },
  { id: 'social', label: 'Sosyal' },
  { id: 'messages', label: 'Mesajlar' },
  { id: 'jobs', label: 'İş İlanları' },
  { id: 'businesses', label: 'İşletmeler' },
  { id: 'emergency', label: 'Acil Durumlar' },
  { id: 'system', label: 'Sistem' },
] as const;

export type NotificationCategoryId = (typeof NOTIFICATION_CATEGORIES)[number]['id'];

export const NOTIFICATION_PRIORITIES = [
  { id: 'low', label: 'Düşük' },
  { id: 'normal', label: 'Normal' },
  { id: 'high', label: 'Yüksek' },
  { id: 'critical', label: 'Kritik' },
] as const;

export type NotificationPriorityId = (typeof NOTIFICATION_PRIORITIES)[number]['id'];

export const EMERGENCY_TYPES = [
  { id: 'fire', label: 'Yangın', emoji: '🚨' },
  { id: 'flood', label: 'Sel', emoji: '🚨' },
  { id: 'landslide', label: 'Heyelan', emoji: '🚨' },
  { id: 'road_closure', label: 'Yol Kapanması', emoji: '🚨' },
  { id: 'power_outage', label: 'Elektrik Kesintisi', emoji: '🚨' },
  { id: 'water_outage', label: 'Su Kesintisi', emoji: '🚨' },
] as const;

export type EmergencyTypeId = (typeof EMERGENCY_TYPES)[number]['id'];

export const NOTIFICATION_EVENT_TYPES = [
  { id: 'like', label: 'Beğeni', prefKey: 'likes', category: 'social' },
  { id: 'comment', label: 'Yorum', prefKey: 'comments', category: 'social' },
  { id: 'comment_reply', label: 'Yorum Yanıtı', prefKey: 'comments', category: 'social' },
  { id: 'quote', label: 'Alıntı', prefKey: 'likes', category: 'social' },
  { id: 'share', label: 'Paylaşım', prefKey: 'likes', category: 'social' },
  { id: 'follow', label: 'Takip', prefKey: 'follows', category: 'social' },
  { id: 'feed_activity', label: 'Canlı Akış', prefKey: 'feed', category: 'social' },
  { id: 'friend_request', label: 'Arkadaşlık İsteği', prefKey: 'friend_requests', category: 'social' },
  { id: 'friend_accepted', label: 'Arkadaş Kabul', prefKey: 'friend_requests', category: 'social' },
  { id: 'account_link_request', label: 'Hesap Bağlama', prefKey: 'system', category: 'system' },
  { id: 'account_link_accepted', label: 'Hesap Bağlandı', prefKey: 'system', category: 'system' },
  { id: 'account_link_declined', label: 'Hesap Bağlama Reddi', prefKey: 'system', category: 'system' },
  { id: 'message', label: 'Mesaj', prefKey: 'messages', category: 'messages' },
  { id: 'group_message', label: 'Grup Mesajı', prefKey: 'messages', category: 'messages' },
  { id: 'mention', label: 'Bahsetme', prefKey: 'mentions', category: 'social' },
  { id: 'reel_like', label: 'Reel Beğeni', prefKey: 'likes', category: 'social' },
  { id: 'call_incoming', label: 'Sesli Arama', prefKey: 'messages', category: 'messages' },
  { id: 'call_video', label: 'Görüntülü Arama', prefKey: 'messages', category: 'messages' },
  { id: 'call_missed', label: 'Kaçırılan Arama', prefKey: 'messages', category: 'messages' },
  { id: 'job', label: 'İş İlanı', prefKey: 'jobs', category: 'jobs' },
  { id: 'business_post', label: 'İşletme Paylaşımı', prefKey: 'businesses', category: 'businesses' },
  { id: 'business_campaign', label: 'Yeni Kampanya', prefKey: 'businesses', category: 'businesses' },
  { id: 'business_event', label: 'İşletme Etkinliği', prefKey: 'businesses', category: 'businesses' },
  { id: 'channel_post', label: 'Kanal Yayını', prefKey: 'channels', category: 'businesses' },
  { id: 'emergency', label: 'Acil Durum', prefKey: 'emergency', category: 'emergency' },
  { id: 'event_nearby', label: 'Yakındaki Etkinlik', prefKey: 'nearby_events', category: 'businesses' },
  { id: 'event_reminder', label: 'Etkinlik Hatırlatması', prefKey: 'nearby_events', category: 'businesses' },
  { id: 'lost_item_nearby', label: 'Yakındaki Kayıp İlanı', prefKey: 'nearby_events', category: 'emergency' },
  { id: 'lost_item_tip', label: 'Kayıp İlanı İpucu', prefKey: 'nearby_events', category: 'emergency' },
  { id: 'incident_update', label: 'Olay Gelişmesi', prefKey: 'nearby_events', category: 'emergency' },
  { id: 'regional_alert', label: 'Bölgesel Uyarı', prefKey: 'nearby_events', category: 'emergency' },
  { id: 'save', label: 'Kaydetme', prefKey: 'likes', category: 'social' },
  { id: 'trust_score_change', label: 'Güven Puanı', prefKey: 'system', category: 'system' },
  { id: 'friend_invite_referral', label: 'Arkadaş Daveti', prefKey: 'system', category: 'system' },
  { id: 'trust_milestone_80', label: 'Güven Puanı 80', prefKey: 'system', category: 'system' },
  { id: 'trust_reward_pool', label: 'Tatil Havuzu', prefKey: 'system', category: 'system' },
  { id: 'achievement_earned', label: 'Başarım', prefKey: 'system', category: 'system' },
  { id: 'badge_earned', label: 'Rozet', prefKey: 'system', category: 'system' },
  { id: 'izdivac_access_granted', label: 'İzdivaç Erişimi', prefKey: 'system', category: 'system' },
  { id: 'izdivac_access_revoked', label: 'İzdivaç Erişim İptali', prefKey: 'system', category: 'system' },
  { id: 'izdivac_post_comment', label: 'İzdivaç Yorumu', prefKey: 'system', category: 'system' },
  { id: 'izdivac_post_join', label: 'İzdivaç Katılım', prefKey: 'system', category: 'system' },
  { id: 'izdivac_invite_received', label: 'İzdivaç Daveti', prefKey: 'system', category: 'system' },
  { id: 'izdivac_invite_accepted', label: 'İzdivaç Davet Kabul', prefKey: 'system', category: 'system' },
  { id: 'security_alert', label: 'Güvenlik Uyarısı', prefKey: 'emergency', category: 'emergency' },
  { id: 'content_warning', label: 'İçerik Uyarısı', prefKey: 'system', category: 'system' },
  { id: 'system', label: 'Sistem Duyurusu', prefKey: 'system', category: 'system' },
  { id: 'marketplace_order_paid', label: 'Pazar Ödemesi', prefKey: 'marketplace', category: 'jobs' },
  { id: 'marketplace_ship_request', label: 'Pazar Teslim', prefKey: 'marketplace', category: 'jobs' },
  { id: 'marketplace_buyer_confirm', label: 'Pazar Onay', prefKey: 'marketplace', category: 'jobs' },
  { id: 'marketplace_platform_approved', label: 'Pazar Onaylandı', prefKey: 'marketplace', category: 'jobs' },
  { id: 'marketplace_payout_due', label: 'Pazar Ödeme', prefKey: 'marketplace', category: 'jobs' },
  { id: 'marketplace_payout_completed', label: 'Pazar Tamamlandı', prefKey: 'marketplace', category: 'jobs' },
  { id: 'marketplace_comment', label: 'Pazar Yorumu', prefKey: 'marketplace', category: 'jobs' },
  { id: 'marketplace_offer', label: 'Pazar Teklifi', prefKey: 'marketplace', category: 'jobs' },
  { id: 'marketplace_offer_accepted', label: 'Pazar Teklifi Kabul', prefKey: 'marketplace', category: 'jobs' },
  { id: 'marketplace_offer_rejected', label: 'Pazar Teklifi Red', prefKey: 'marketplace', category: 'jobs' },
  { id: 'ride_reservation_new', label: 'Yolculuk Rezervasyonu', prefKey: 'rides', category: 'jobs' },
  { id: 'ride_reservation_paid', label: 'Yolculuk Ödemesi', prefKey: 'rides', category: 'jobs' },
  { id: 'ride_reservation_approved', label: 'Rezervasyon Onayı', prefKey: 'rides', category: 'jobs' },
  { id: 'ride_reservation_rejected', label: 'Rezervasyon Reddi', prefKey: 'rides', category: 'jobs' },
  { id: 'ride_passenger_cancelled_reservation', label: 'Yolcu İptali (Sürücü)', prefKey: 'rides', category: 'jobs' },
  { id: 'ride_trip_cancelled', label: 'Yolculuk İptali', prefKey: 'rides', category: 'jobs' },
  { id: 'ride_trip_started', label: 'Yolculuk Başladı', prefKey: 'rides', category: 'jobs' },
  { id: 'ride_trip_completed', label: 'Yolculuk Tamamlandı', prefKey: 'rides', category: 'jobs' },
  { id: 'ride_trip_starting_soon', label: 'Yolculuk Hatırlatma', prefKey: 'rides', category: 'jobs' },
  { id: 'ride_trip_departure_soon', label: 'Kalkışa 15 Dk', prefKey: 'rides', category: 'jobs' },
  { id: 'ride_trip_departure_due', label: 'Kalkış Saati', prefKey: 'rides', category: 'jobs' },
  { id: 'ride_trip_complete_soon', label: 'Yolculuk Bitişi', prefKey: 'rides', category: 'jobs' },
  { id: 'ride_payout_due', label: 'Sürücü Ödeme Planı', prefKey: 'rides', category: 'jobs' },
  { id: 'ride_payout_completed', label: 'Sürücü Ödemesi', prefKey: 'rides', category: 'jobs' },
  { id: 'ride_live_location_shared', label: 'Canlı Konum', prefKey: 'rides', category: 'jobs' },
  { id: 'vora_need_published', label: 'İhtiyaç Ağı', prefKey: 'vora_needs', category: 'jobs' },
  { id: 'vora_service_request_published', label: 'Hizmet Talebi', prefKey: 'vora_hizmetler', category: 'jobs' },
  { id: 'vora_service_offer_received', label: 'Yeni Hizmet Teklifi', prefKey: 'vora_hizmetler', category: 'jobs' },
  { id: 'vora_service_offer_accepted', label: 'Hizmet Teklifi Kabul', prefKey: 'vora_hizmetler', category: 'jobs' },
  { id: 'vora_service_offer_rejected', label: 'Hizmet Teklifi Red', prefKey: 'vora_hizmetler', category: 'jobs' },
  { id: 'vora_service_request_invite', label: 'Hizmet Daveti', prefKey: 'vora_hizmetler', category: 'jobs' },
  { id: 'vora_service_job_started', label: 'Hizmet İşi Başladı', prefKey: 'vora_hizmetler', category: 'jobs' },
  { id: 'vora_service_job_completed', label: 'Hizmet İş Tamamlandı', prefKey: 'vora_hizmetler', category: 'jobs' },
  { id: 'vora_service_completion_proof', label: 'Hizmet Tamamlama Kanıtı', prefKey: 'vora_hizmetler', category: 'jobs' },
  { id: 'vora_service_payout_due', label: 'Hizmet Ödeme Planı', prefKey: 'vora_hizmetler', category: 'jobs' },
  { id: 'vora_service_payout_completed', label: 'Hizmet Ödemesi', prefKey: 'vora_hizmetler', category: 'jobs' },
  { id: 'vora_service_emergency_call', label: 'Acil Hizmet', prefKey: 'vora_hizmetler', category: 'emergency' },
  { id: 'hotel_review', label: 'Otel Değerlendirmesi', prefKey: 'hotels', category: 'businesses' },
  { id: 'hotel_reservation_paid', label: 'Otel Rezervasyon Onayı', prefKey: 'hotels', category: 'businesses' },
  { id: 'hotel_reservation_received', label: 'Otel Rezervasyonu (Sahip)', prefKey: 'hotels', category: 'businesses' },
  { id: 'hotel_reservation_cancelled', label: 'Otel Rezervasyon İptali', prefKey: 'hotels', category: 'businesses' },
  { id: 'hotel_payout_due', label: 'Otel Ödeme Planı', prefKey: 'hotels', category: 'jobs' },
  { id: 'hotel_payout_completed', label: 'Otel Kazanç Yatırıldı', prefKey: 'hotels', category: 'jobs' },
  { id: 'hotel_marketing_campaign', label: 'Otel Kampanyası', prefKey: 'hotels', category: 'businesses' },
] as const;

export type NotificationEventType = (typeof NOTIFICATION_EVENT_TYPES)[number]['id'];

/** Push gider; bildirim kutusunda gösterilmez (Mesajlar sekmesinde takip edilir). */
export const INBOX_EXCLUDED_EVENT_TYPES = ['message', 'group_message'] as const satisfies readonly NotificationEventType[];

export function isInboxExcludedNotification(
  eventType: NotificationEventType,
  data?: Record<string, unknown> | null,
): boolean {
  if (!INBOX_EXCLUDED_EVENT_TYPES.includes(eventType as (typeof INBOX_EXCLUDED_EVENT_TYPES)[number])) {
    return false;
  }
  return !!data?.conversation_id;
}

export const MAX_NOTIFICATION_SOUND_SECONDS = 10;

export const PUSH_PREF_OPTIONS = [
  { id: 'likes', label: 'Beğeniler', description: 'Gönderi ve reel beğenileri, paylaşımlar' },
  { id: 'comments', label: 'Yorumlar', description: 'Yorum ve yanıtlar' },
  { id: 'follows', label: 'Takip', description: 'Yeni takipçiler' },
  { id: 'friend_requests', label: 'Arkadaşlık', description: 'Arkadaşlık istekleri ve kabul' },
  { id: 'messages', label: 'Mesajlar', description: 'Yeni mesajlar ve aramalar' },
  { id: 'mentions', label: 'Bahsetmeler', description: 'Sizi etiketleyen paylaşımlar' },
  { id: 'feed', label: 'Canlı akış', description: 'Bölgenizde yeni paylaşımlar — Vora çok canlı bildirimleri' },
  { id: 'channels', label: 'Kanallar', description: 'Abone olduğunuz kanal yayınları' },
  { id: 'businesses', label: 'İşletmeler', description: 'Takip ettiğiniz işletme paylaşımları ve kampanyaları' },
  { id: 'nearby_events', label: 'Yakındaki olaylar', description: 'Bölgesel olay ve gelişmeler' },
  { id: 'emergency', label: 'Acil durum', description: 'Kritik uyarılar (sessiz saatte de gelir)' },
  { id: 'jobs', label: 'İş ilanları', description: 'Başvuru ve yeni iş fırsatları' },
  { id: 'marketplace', label: 'Yerel Pazar', description: 'Teklif, sipariş, teslim ve ödeme bildirimleri' },
  { id: 'rides', label: 'Paylaşımlı Yolculuk', description: 'Rezervasyon, yolculuk ve canlı konum bildirimleri' },
  { id: 'vora_needs', label: 'İhtiyaç Ağı', description: 'Yakınınızdaki yeni ihtiyaç ve yardım ilanları' },
  { id: 'vora_hizmetler', label: 'Vora Hizmetler', description: 'Kategori ve şehre göre yeni iş talepleri, teklifler ve acil çağrılar' },
  { id: 'hotels', label: 'Otel Merkezi', description: 'Rezervasyon, değerlendirme ve öne çıkan otel kampanyaları' },
  { id: 'system', label: 'Sistem', description: 'Güncelleme, güven puanı, rozet, hesap bağlama ve duyurular' },
] as const;

export type PushPrefId = (typeof PUSH_PREF_OPTIONS)[number]['id'];

export const EVENT_CATEGORY_MAP: Record<string, NotificationCategoryId> = {
  like: 'social',
  comment: 'social',
  comment_reply: 'social',
  quote: 'social',
  share: 'social',
  follow: 'social',
  feed_activity: 'social',
  friend_request: 'social',
  friend_accepted: 'social',
  account_link_request: 'system',
  account_link_accepted: 'system',
  account_link_declined: 'system',
  mention: 'social',
  reel_like: 'social',
  save: 'social',
  channel_post: 'businesses',
  message: 'messages',
  group_message: 'messages',
  call_incoming: 'messages',
  call_video: 'messages',
  call_missed: 'messages',
  job: 'jobs',
  business_post: 'businesses',
  business_campaign: 'businesses',
  business_event: 'businesses',
  event_nearby: 'businesses',
  event_reminder: 'businesses',
  lost_item_nearby: 'emergency',
  lost_item_tip: 'emergency',
  emergency: 'emergency',
  regional_alert: 'emergency',
  incident_update: 'emergency',
  security_alert: 'emergency',
  content_warning: 'system',
  trust_score_change: 'system',
  friend_invite_referral: 'system',
  trust_milestone_80: 'system',
  trust_reward_pool: 'system',
  achievement_earned: 'system',
  badge_earned: 'system',
  izdivac_access_granted: 'system',
  izdivac_access_revoked: 'system',
  izdivac_post_comment: 'system',
  izdivac_post_join: 'system',
  izdivac_invite_received: 'system',
  izdivac_invite_accepted: 'system',
  system: 'system',
  marketplace_order_paid: 'jobs',
  marketplace_ship_request: 'jobs',
  marketplace_buyer_confirm: 'jobs',
  marketplace_platform_approved: 'jobs',
  marketplace_payout_due: 'jobs',
  marketplace_payout_completed: 'jobs',
  marketplace_comment: 'jobs',
  marketplace_offer: 'jobs',
  marketplace_offer_accepted: 'jobs',
  marketplace_offer_rejected: 'jobs',
  ride_reservation_new: 'jobs',
  ride_reservation_paid: 'jobs',
  ride_reservation_approved: 'jobs',
  ride_reservation_rejected: 'jobs',
  ride_passenger_cancelled_reservation: 'jobs',
  ride_trip_cancelled: 'jobs',
  ride_trip_started: 'jobs',
  ride_trip_completed: 'jobs',
  ride_trip_starting_soon: 'jobs',
  ride_trip_departure_soon: 'jobs',
  ride_trip_departure_due: 'jobs',
  ride_trip_complete_soon: 'jobs',
  ride_payout_due: 'jobs',
  ride_payout_completed: 'jobs',
  ride_live_location_shared: 'jobs',
  vora_need_published: 'jobs',
  vora_service_request_published: 'jobs',
  vora_service_offer_received: 'jobs',
  vora_service_offer_accepted: 'jobs',
  vora_service_offer_rejected: 'jobs',
  vora_service_request_invite: 'jobs',
  vora_service_job_started: 'jobs',
  vora_service_job_completed: 'jobs',
  vora_service_completion_proof: 'jobs',
  vora_service_payout_due: 'jobs',
  vora_service_payout_completed: 'jobs',
  vora_service_emergency_call: 'emergency',
  hotel_review: 'businesses',
  hotel_reservation_paid: 'businesses',
  hotel_reservation_received: 'businesses',
  hotel_reservation_cancelled: 'businesses',
  hotel_payout_due: 'jobs',
  hotel_payout_completed: 'jobs',
  hotel_marketing_campaign: 'businesses',
};

export function emergencyLabel(type?: string): string {
  const found = EMERGENCY_TYPES.find((t) => t.id === type);
  return found ? `${found.emoji} ${found.label}` : '🚨 Acil Durum';
}
