export const LOBBY_FEEDBACK_MIN_NAME_LENGTH = 2;
export const LOBBY_FEEDBACK_MIN_MESSAGE_LENGTH = 10;
export const LOBBY_FEEDBACK_MAX_MESSAGE_LENGTH = 2000;
export const LOBBY_FEEDBACK_MAX_NAME_LENGTH = 120;
